package services

import "strings"

// JapaneseToEnglishNames maps Japanese Pokemon and card names to their English equivalents.
// This enables matching scanned Japanese cards against the English database.
// Data sourced from PokeAPI (pokemon_species_names.csv) - verified official names.
var JapaneseToEnglishNames = map[string]string{

	// Gen 1 Pokemon (001-151)
	"フシギダネ": "Bulbasaur",
	"フシギソウ": "Ivysaur",
	"フシギバナ": "Venusaur",
	"ヒトカゲ":  "Charmander",
	"リザード":  "Charmeleon",
	"リザードン": "Charizard",
	"ゼニガメ":  "Squirtle",
	"カメール":  "Wartortle",
	"カメックス": "Blastoise",
	"キャタピー": "Caterpie",
	"トランセル": "Metapod",
	"バタフリー": "Butterfree",
	"ビードル":  "Weedle",
	"コクーン":  "Kakuna",
	"スピアー":  "Beedrill",
	"ポッポ":   "Pidgey",
	"ピジョン":  "Pidgeotto",
	"ピジョット": "Pidgeot",
	"コラッタ":  "Rattata",
	"ラッタ":   "Raticate",
	"オニスズメ": "Spearow",
	"オニドリル": "Fearow",
	"アーボ":   "Ekans",
	"アーボック": "Arbok",
	"ピカチュウ": "Pikachu",
	"ライチュウ": "Raichu",
	"サンド":   "Sandshrew",
	"サンドパン": "Sandslash",
	"ニドラン♀": "Nidoran ♀",
	"ニドリーナ": "Nidorina",
	"ニドクイン": "Nidoqueen",
	"ニドラン♂": "Nidoran ♂",
	"ニドリーノ": "Nidorino",
	"ニドキング": "Nidoking",
	"ピッピ":   "Clefairy",
	"ピクシー":  "Clefable",
	"ロコン":   "Vulpix",
	"キュウコン": "Ninetales",
	"プリン":   "Jigglypuff",
	"プクリン":  "Wigglytuff",
	"ズバット":  "Zubat",
	"ゴルバット": "Golbat",
	"ナゾノクサ": "Oddish",
	"クサイハナ": "Gloom",
	"ラフレシア": "Vileplume",
	"パラス":   "Paras",
	"パラセクト": "Parasect",
	"コンパン":  "Venonat",
	"モルフォン": "Venomoth",
	"ディグダ":  "Diglett",
	"ダグトリオ": "Dugtrio",
	"ニャース":  "Meowth",
	"ペルシアン": "Persian",
	"コダック":  "Psyduck",
	"ゴルダック": "Golduck",
	"マンキー":  "Mankey",
	"オコリザル": "Primeape",
	"ガーディ":  "Growlithe",
	"ウインディ": "Arcanine",
	"ニョロモ":  "Poliwag",
	"ニョロゾ":  "Poliwhirl",
	"ニョロボン": "Poliwrath",
	"ケーシィ":  "Abra",
	"ユンゲラー": "Kadabra",
	"フーディン": "Alakazam",
	"ワンリキー": "Machop",
	"ゴーリキー": "Machoke",
	"カイリキー": "Machamp",
	"マダツボミ": "Bellsprout",
	"ウツドン":  "Weepinbell",
	"ウツボット": "Victreebel",
	"メノクラゲ": "Tentacool",
	"ドククラゲ": "Tentacruel",
	"イシツブテ": "Geodude",
	"ゴローン":  "Graveler",
	"ゴローニャ": "Golem",
	"ポニータ":  "Ponyta",
	"ギャロップ": "Rapidash",
	"ヤドン":   "Slowpoke",
	"ヤドラン":  "Slowbro",
	"コイル":   "Magnemite",
	"レアコイル": "Magneton",
	"カモネギ":  "Farfetch'd",
	"ドードー":  "Doduo",
	"ドードリオ": "Dodrio",
	"パウワウ":  "Seel",
	"ジュゴン":  "Dewgong",
	"ベトベター": "Grimer",
	"ベトベトン": "Muk",
	"シェルダー": "Shellder",
	"パルシェン": "Cloyster",
	"ゴース":   "Gastly",
	"ゴースト":  "Haunter",
	"ゲンガー":  "Gengar",
	"イワーク":  "Onix",
	"スリープ":  "Drowzee",
	"スリーパー": "Hypno",
	"クラブ":   "Krabby",
	"キングラー": "Kingler",
	"ビリリダマ": "Voltorb",
	"マルマイン": "Electrode",
	"タマタマ":  "Exeggcute",
	"ナッシー":  "Exeggutor",
	"カラカラ":  "Cubone",
	"ガラガラ":  "Marowak",
	"サワムラー": "Hitmonlee",
	"エビワラー": "Hitmonchan",
	"ベロリンガ": "Lickitung",
	"ドガース":  "Koffing",
	"マタドガス": "Weezing",
	"サイホーン": "Rhyhorn",
	"サイドン":  "Rhydon",
	"ラッキー":  "Chansey",
	"モンジャラ": "Tangela",
	"ガルーラ":  "Kangaskhan",
	"タッツー":  "Horsea",
	"シードラ":  "Seadra",
	"トサキント": "Goldeen",
	"アズマオウ": "Seaking",
	"ヒトデマン": "Staryu",
	"スターミー": "Starmie",
	"バリヤード": "Mr. Mime",
	"ストライク": "Scyther",
	"ルージュラ": "Jynx",
	"エレブー":  "Electabuzz",
	"ブーバー":  "Magmar",
	"カイロス":  "Pinsir",
	"ケンタロス": "Tauros",
	"コイキング": "Magikarp",
	"ギャラドス": "Gyarados",
	"ラプラス":  "Lapras",
	"メタモン":  "Ditto",
	"イーブイ":  "Eevee",
	"シャワーズ": "Vaporeon",
	"サンダース": "Jolteon",
	"ブースター": "Flareon",
	"ポリゴン":  "Porygon",
	"オムナイト": "Omanyte",
	"オムスター": "Omastar",
	"カブト":   "Kabuto",
	"カブトプス": "Kabutops",
	"プテラ":   "Aerodactyl",
	"カビゴン":  "Snorlax",
	"フリーザー": "Articuno",
	"サンダー":  "Zapdos",
	"ファイヤー": "Moltres",
	"ミニリュウ": "Dratini",
	"ハクリュー": "Dragonair",
	"カイリュー": "Dragonite",
	"ミュウツー": "Mewtwo",
	"ミュウ":   "Mew",

	// Gen 2 Pokemon (152-251)
	"チコリータ": "Chikorita",
	"ベイリーフ": "Bayleef",
	"メガニウム": "Meganium",
	"ヒノアラシ": "Cyndaquil",
	"マグマラシ": "Quilava",
	"バクフーン": "Typhlosion",
	"ワニノコ":  "Totodile",
	"アリゲイツ": "Croconaw",
	"オーダイル": "Feraligatr",
	"オタチ":   "Sentret",
	"オオタチ":  "Furret",
	"ホーホー":  "Hoothoot",
	"ヨルノズク": "Noctowl",
	"レディバ":  "Ledyba",
	"レディアン": "Ledian",
	"イトマル":  "Spinarak",
	"アリアドス": "Ariados",
	"クロバット": "Crobat",
	"チョンチー": "Chinchou",
	"ランターン": "Lanturn",
	"ピチュー":  "Pichu",
	"ピィ":    "Cleffa",
	"ププリン":  "Igglybuff",
	"トゲピー":  "Togepi",
	"トゲチック": "Togetic",
	"ネイティ":  "Natu",
	"ネイティオ": "Xatu",
	"メリープ":  "Mareep",
	"モココ":   "Flaaffy",
	"デンリュウ": "Ampharos",
	"キレイハナ": "Bellossom",
	"マリル":   "Marill",
	"マリルリ":  "Azumarill",
	"ウソッキー": "Sudowoodo",
	"ニョロトノ": "Politoed",
	"ハネッコ":  "Hoppip",
	"ポポッコ":  "Skiploom",
	"ワタッコ":  "Jumpluff",
	"エイパム":  "Aipom",
	"ヒマナッツ": "Sunkern",
	"キマワリ":  "Sunflora",
	"ヤンヤンマ": "Yanma",
	"ウパー":   "Wooper",
	"ヌオー":   "Quagsire",
	"エーフィ":  "Espeon",
	"ブラッキー": "Umbreon",
	"ヤミカラス": "Murkrow",
	"ヤドキング": "Slowking",
	"ムウマ":   "Misdreavus",
	"アンノーン": "Unown",
	"ソーナンス": "Wobbuffet",
	"キリンリキ": "Girafarig",
	"クヌギダマ": "Pineco",
	"フォレトス": "Forretress",
	"ノコッチ":  "Dunsparce",
	"グライガー": "Gligar",
	"ハガネール": "Steelix",
	"ブルー":   "Snubbull",
	"グランブル": "Granbull",
	"ハリーセン": "Qwilfish",
	"ハッサム":  "Scizor",
	"ツボツボ":  "Shuckle",
	"ヘラクロス": "Heracross",
	"ニューラ":  "Sneasel",
	"ヒメグマ":  "Teddiursa",
	"リングマ":  "Ursaring",
	"マグマッグ": "Slugma",
	"マグカルゴ": "Magcargo",
	"ウリムー":  "Swinub",
	"イノムー":  "Piloswine",
	"サニーゴ":  "Corsola",
	"テッポウオ": "Remoraid",
	"オクタン":  "Octillery",
	"デリバード": "Delibird",
	"マンタイン": "Mantine",
	"エアームド": "Skarmory",
	"デルビル":  "Houndour",
	"ヘルガー":  "Houndoom",
	"キングドラ": "Kingdra",
	"ゴマゾウ":  "Phanpy",
	"ドンファン": "Donphan",
	"ポリゴン２": "Porygon2",
	"オドシシ":  "Stantler",
	"ドーブル":  "Smeargle",
	"バルキー":  "Tyrogue",
	"カポエラー": "Hitmontop",
	"ムチュール": "Smoochum",
	"エレキッド": "Elekid",
	"ブビィ":   "Magby",
	"ミルタンク": "Miltank",
	"ハピナス":  "Blissey",
	"ライコウ":  "Raikou",
	"エンテイ":  "Entei",
	"スイクン":  "Suicune",
	"ヨーギラス": "Larvitar",
	"サナギラス": "Pupitar",
	"バンギラス": "Tyranitar",
	"ルギア":   "Lugia",
	"ホウオウ":  "Ho-Oh",
	"セレビィ":  "Celebi",

	// Gen 3 Pokemon (252-386)
	"キモリ":   "Treecko",
	"ジュプトル": "Grovyle",
	"ジュカイン": "Sceptile",
	"アチャモ":  "Torchic",
	"ワカシャモ": "Combusken",
	"バシャーモ": "Blaziken",
	"ミズゴロウ": "Mudkip",
	"ヌマクロー": "Marshtomp",
	"ラグラージ": "Swampert",
	"ポチエナ":  "Poochyena",
	"グラエナ":  "Mightyena",
	"ジグザグマ": "Zigzagoon",
	"マッスグマ": "Linoone",
	"ケムッソ":  "Wurmple",
	"カラサリス": "Silcoon",
	"アゲハント": "Beautifly",
	"マユルド":  "Cascoon",
	"ドクケイル": "Dustox",
	"ハスボー":  "Lotad",
	"ハスブレロ": "Lombre",
	"ルンパッパ": "Ludicolo",
	"タネボー":  "Seedot",
	"コノハナ":  "Nuzleaf",
	"ダーテング": "Shiftry",
	"スバメ":   "Taillow",
	"オオスバメ": "Swellow",
	"キャモメ":  "Wingull",
	"ペリッパー": "Pelipper",
	"ラルトス":  "Ralts",
	"キルリア":  "Kirlia",
	"サーナイト": "Gardevoir",
	"アメタマ":  "Surskit",
	"アメモース": "Masquerain",
	"キノココ":  "Shroomish",
	"キノガッサ": "Breloom",
	"ナマケロ":  "Slakoth",
	"ヤルキモノ": "Vigoroth",
	"ケッキング": "Slaking",
	"ツチニン":  "Nincada",
	"テッカニン": "Ninjask",
	"ヌケニン":  "Shedinja",
	"ゴニョニョ": "Whismur",
	"ドゴーム":  "Loudred",
	"バクオング": "Exploud",
	"マクノシタ": "Makuhita",
	"ハリテヤマ": "Hariyama",
	"ルリリ":   "Azurill",
	"ノズパス":  "Nosepass",
	"エネコ":   "Skitty",
	"エネコロロ": "Delcatty",
	"ヤミラミ":  "Sableye",
	"クチート":  "Mawile",
	"ココドラ":  "Aron",
	"コドラ":   "Lairon",
	"ボスゴドラ": "Aggron",
	"アサナン":  "Meditite",
	"チャーレム": "Medicham",
	"ラクライ":  "Electrike",
	"ライボルト": "Manectric",
	"プラスル":  "Plusle",
	"マイナン":  "Minun",
	"バルビート": "Volbeat",
	"イルミーゼ": "Illumise",
	"ロゼリア":  "Roselia",
	"ゴクリン":  "Gulpin",
	"マルノーム": "Swalot",
	"キバニア":  "Carvanha",
	"サメハダー": "Sharpedo",
	"ホエルコ":  "Wailmer",
	"ホエルオー": "Wailord",
	"ドンメル":  "Numel",
	"バクーダ":  "Camerupt",
	"コータス":  "Torkoal",
	"バネブー":  "Spoink",
	"ブーピッグ": "Grumpig",
	"パッチール": "Spinda",
	"ナックラー": "Trapinch",
	"ビブラーバ": "Vibrava",
	"フライゴン": "Flygon",
	"サボネア":  "Cacnea",
	"ノクタス":  "Cacturne",
	"チルット":  "Swablu",
	"チルタリス": "Altaria",
	"ザングース": "Zangoose",
	"ハブネーク": "Seviper",
	"ルナトーン": "Lunatone",
	"ソルロック": "Solrock",
	"ドジョッチ": "Barboach",
	"ナマズン":  "Whiscash",
	"ヘイガニ":  "Corphish",
	"シザリガー": "Crawdaunt",
	"ヤジロン":  "Baltoy",
	"ネンドール": "Claydol",
	"リリーラ":  "Lileep",
	"ユレイドル": "Cradily",
	"アノプス":  "Anorith",
	"アーマルド": "Armaldo",
	"ヒンバス":  "Feebas",
	"ミロカロス": "Milotic",
	"ポワルン":  "Castform",
	"カクレオン": "Kecleon",
	"カゲボウズ": "Shuppet",
	"ジュペッタ": "Banette",
	"ヨマワル":  "Duskull",
	"サマヨール": "Dusclops",
	"トロピウス": "Tropius",
	"チリーン":  "Chimecho",
	"アブソル":  "Absol",
	"ソーナノ":  "Wynaut",
	"ユキワラシ": "Snorunt",
	"オニゴーリ": "Glalie",
	"タマザラシ": "Spheal",
	"トドグラー": "Sealeo",
	"トドゼルガ": "Walrein",
	"パールル":  "Clamperl",
	"ハンテール": "Huntail",
	"サクラビス": "Gorebyss",
	"ジーランス": "Relicanth",
	"ラブカス":  "Luvdisc",
	"タツベイ":  "Bagon",
	"コモルー":  "Shelgon",
	"ボーマンダ": "Salamence",
	"ダンバル":  "Beldum",
	"メタング":  "Metang",
	"メタグロス": "Metagross",
	"レジロック": "Regirock",
	"レジアイス": "Regice",
	"レジスチル": "Registeel",
	"ラティアス": "Latias",
	"ラティオス": "Latios",
	"カイオーガ": "Kyogre",
	"グラードン": "Groudon",
	"レックウザ": "Rayquaza",
	"ジラーチ":  "Jirachi",
	"デオキシス": "Deoxys",

	// Gen 4 Pokemon (387-493)
	"ナエトル":  "Turtwig",
	"ハヤシガメ": "Grotle",
	"ドダイトス": "Torterra",
	"ヒコザル":  "Chimchar",
	"モウカザル": "Monferno",
	"ゴウカザル": "Infernape",
	"ポッチャマ": "Piplup",
	"ポッタイシ": "Prinplup",
	"エンペルト": "Empoleon",
	"ムックル":  "Starly",
	"ムクバード": "Staravia",
	"ムクホーク": "Staraptor",
	"ビッパ":   "Bidoof",
	"ビーダル":  "Bibarel",
	"コロボーシ": "Kricketot",
	"コロトック": "Kricketune",
	"コリンク":  "Shinx",
	"ルクシオ":  "Luxio",
	"レントラー": "Luxray",
	"スボミー":  "Budew",
	"ロズレイド": "Roserade",
	"ズガイドス": "Cranidos",
	"ラムパルド": "Rampardos",
	"タテトプス": "Shieldon",
	"トリデプス": "Bastiodon",
	"ミノムッチ": "Burmy",
	"ミノマダム": "Wormadam",
	"ガーメイル": "Mothim",
	"ミツハニー": "Combee",
	"ビークイン": "Vespiquen",
	"パチリス":  "Pachirisu",
	"ブイゼル":  "Buizel",
	"フローゼル": "Floatzel",
	"チェリンボ": "Cherubi",
	"チェリム":  "Cherrim",
	"カラナクシ": "Shellos",
	"トリトドン": "Gastrodon",
	"エテボース": "Ambipom",
	"フワンテ":  "Drifloon",
	"フワライド": "Drifblim",
	"ミミロル":  "Buneary",
	"ミミロップ": "Lopunny",
	"ムウマージ": "Mismagius",
	"ドンカラス": "Honchkrow",
	"ニャルマー": "Glameow",
	"ブニャット": "Purugly",
	"リーシャン": "Chingling",
	"スカンプー": "Stunky",
	"スカタンク": "Skuntank",
	"ドーミラー": "Bronzor",
	"ドータクン": "Bronzong",
	"ウソハチ":  "Bonsly",
	"マネネ":   "Mime Jr.",
	"ピンプク":  "Happiny",
	"ペラップ":  "Chatot",
	"ミカルゲ":  "Spiritomb",
	"フカマル":  "Gible",
	"ガバイト":  "Gabite",
	"ガブリアス": "Garchomp",
	"ゴンベ":   "Munchlax",
	"リオル":   "Riolu",
	"ルカリオ":  "Lucario",
	"ヒポポタス": "Hippopotas",
	"カバルドン": "Hippowdon",
	"スコルピ":  "Skorupi",
	"ドラピオン": "Drapion",
	"グレッグル": "Croagunk",
	"ドクロッグ": "Toxicroak",
	"マスキッパ": "Carnivine",
	"ケイコウオ": "Finneon",
	"ネオラント": "Lumineon",
	"タマンタ":  "Mantyke",
	"ユキカブリ": "Snover",
	"ユキノオー": "Abomasnow",
	"マニューラ": "Weavile",
	"ジバコイル": "Magnezone",
	"ベロベルト": "Lickilicky",
	"ドサイドン": "Rhyperior",
	"モジャンボ": "Tangrowth",
	"エレキブル": "Electivire",
	"ブーバーン": "Magmortar",
	"トゲキッス": "Togekiss",
	"メガヤンマ": "Yanmega",
	"リーフィア": "Leafeon",
	"グレイシア": "Glaceon",
	"グライオン": "Gliscor",
	"マンムー":  "Mamoswine",
	"ポリゴンＺ": "Porygon-Z",
	"エルレイド": "Gallade",
	"ダイノーズ": "Probopass",
	"ヨノワール": "Dusknoir",
	"ユキメノコ": "Froslass",
	"ロトム":   "Rotom",
	"ユクシー":  "Uxie",
	"エムリット": "Mesprit",
	"アグノム":  "Azelf",
	"ディアルガ": "Dialga",
	"パルキア":  "Palkia",
	"ヒードラン": "Heatran",
	"レジギガス": "Regigigas",
	"ギラティナ": "Giratina",
	"クレセリア": "Cresselia",
	"フィオネ":  "Phione",
	"マナフィ":  "Manaphy",
	"ダークライ": "Darkrai",
	"シェイミ":  "Shaymin",
	"アルセウス": "Arceus",

	// Gen 5 Pokemon (494-649)
	"ビクティニ": "Victini",
	"ツタージャ": "Snivy",
	"ジャノビー": "Servine",
	"ジャローダ": "Serperior",
	"ポカブ":   "Tepig",
	"チャオブー": "Pignite",
	"エンブオー": "Emboar",
	"ミジュマル": "Oshawott",
	"フタチマル": "Dewott",
	"ダイケンキ": "Samurott",
	"ミネズミ":  "Patrat",
	"ミルホッグ": "Watchog",
	"ヨーテリー": "Lillipup",
	"ハーデリア": "Herdier",
	"ムーランド": "Stoutland",
	"チョロネコ": "Purrloin",
	"レパルダス": "Liepard",
	"ヤナップ":  "Pansage",
	"ヤナッキー": "Simisage",
	"バオップ":  "Pansear",
	"バオッキー": "Simisear",
	"ヒヤップ":  "Panpour",
	"ヒヤッキー": "Simipour",
	"ムンナ":   "Munna",
	"ムシャーナ": "Musharna",
	"マメパト":  "Pidove",
	"ハトーボー": "Tranquill",
	"ケンホロウ": "Unfezant",
	"シママ":   "Blitzle",
	"ゼブライカ": "Zebstrika",
	"ダンゴロ":  "Roggenrola",
	"ガントル":  "Boldore",
	"ギガイアス": "Gigalith",
	"コロモリ":  "Woobat",
	"ココロモリ": "Swoobat",
	"モグリュー": "Drilbur",
	"ドリュウズ": "Excadrill",
	"タブンネ":  "Audino",
	"ドッコラー": "Timburr",
	"ドテッコツ": "Gurdurr",
	"ローブシン": "Conkeldurr",
	"オタマロ":  "Tympole",
	"ガマガル":  "Palpitoad",
	"ガマゲロゲ": "Seismitoad",
	"ナゲキ":   "Throh",
	"ダゲキ":   "Sawk",
	"クルミル":  "Sewaddle",
	"クルマユ":  "Swadloon",
	"ハハコモリ": "Leavanny",
	"フシデ":   "Venipede",
	"ホイーガ":  "Whirlipede",
	"ペンドラー": "Scolipede",
	"モンメン":  "Cottonee",
	"エルフーン": "Whimsicott",
	"チュリネ":  "Petilil",
	"ドレディア": "Lilligant",
	"バスラオ":  "Basculin",
	"メグロコ":  "Sandile",
	"ワルビル":  "Krokorok",
	"ワルビアル": "Krookodile",
	"ダルマッカ": "Darumaka",
	"ヒヒダルマ": "Darmanitan",
	"マラカッチ": "Maractus",
	"イシズマイ": "Dwebble",
	"イワパレス": "Crustle",
	"ズルッグ":  "Scraggy",
	"ズルズキン": "Scrafty",
	"シンボラー": "Sigilyph",
	"デスマス":  "Yamask",
	"デスカーン": "Cofagrigus",
	"プロトーガ": "Tirtouga",
	"アバゴーラ": "Carracosta",
	"アーケン":  "Archen",
	"アーケオス": "Archeops",
	"ヤブクロン": "Trubbish",
	"ダストダス": "Garbodor",
	"ゾロア":   "Zorua",
	"ゾロアーク": "Zoroark",
	"チラーミィ": "Minccino",
	"チラチーノ": "Cinccino",
	"ゴチム":   "Gothita",
	"ゴチミル":  "Gothorita",
	"ゴチルゼル": "Gothitelle",
	"ユニラン":  "Solosis",
	"ダブラン":  "Duosion",
	"ランクルス": "Reuniclus",
	"コアルヒー": "Ducklett",
	"スワンナ":  "Swanna",
	"バニプッチ": "Vanillite",
	"バニリッチ": "Vanillish",
	"バイバニラ": "Vanilluxe",
	"シキジカ":  "Deerling",
	"メブキジカ": "Sawsbuck",
	"エモンガ":  "Emolga",
	"カブルモ":  "Karrablast",
	"シュバルゴ": "Escavalier",
	"タマゲタケ": "Foongus",
	"モロバレル": "Amoonguss",
	"プルリル":  "Frillish",
	"ブルンゲル": "Jellicent",
	"ママンボウ": "Alomomola",
	"バチュル":  "Joltik",
	"デンチュラ": "Galvantula",
	"テッシード": "Ferroseed",
	"ナットレイ": "Ferrothorn",
	"ギアル":   "Klink",
	"ギギアル":  "Klang",
	"ギギギアル": "Klinklang",
	"シビシラス": "Tynamo",
	"シビビール": "Eelektrik",
	"シビルドン": "Eelektross",
	"リグレー":  "Elgyem",
	"オーベム":  "Beheeyem",
	"ヒトモシ":  "Litwick",
	"ランプラー": "Lampent",
	"シャンデラ": "Chandelure",
	"キバゴ":   "Axew",
	"オノンド":  "Fraxure",
	"オノノクス": "Haxorus",
	"クマシュン": "Cubchoo",
	"ツンベアー": "Beartic",
	"フリージオ": "Cryogonal",
	"チョボマキ": "Shelmet",
	"アギルダー": "Accelgor",
	"マッギョ":  "Stunfisk",
	"コジョフー": "Mienfoo",
	"コジョンド": "Mienshao",
	"クリムガン": "Druddigon",
	"ゴビット":  "Golett",
	"ゴルーグ":  "Golurk",
	"コマタナ":  "Pawniard",
	"キリキザン": "Bisharp",
	"バッフロン": "Bouffalant",
	"ワシボン":  "Rufflet",
	"ウォーグル": "Braviary",
	"バルチャイ": "Vullaby",
	"バルジーナ": "Mandibuzz",
	"クイタラン": "Heatmor",
	"アイアント": "Durant",
	"モノズ":   "Deino",
	"ジヘッド":  "Zweilous",
	"サザンドラ": "Hydreigon",
	"メラルバ":  "Larvesta",
	"ウルガモス": "Volcarona",
	"コバルオン": "Cobalion",
	"テラキオン": "Terrakion",
	"ビリジオン": "Virizion",
	"トルネロス": "Tornadus",
	"ボルトロス": "Thundurus",
	"レシラム":  "Reshiram",
	"ゼクロム":  "Zekrom",
	"ランドロス": "Landorus",
	"キュレム":  "Kyurem",
	"ケルディオ": "Keldeo",
	"メロエッタ": "Meloetta",
	"ゲノセクト": "Genesect",

	// Gen 6 Pokemon (650-721)
	"ハリマロン":  "Chespin",
	"ハリボーグ":  "Quilladin",
	"ブリガロン":  "Chesnaught",
	"フォッコ":   "Fennekin",
	"テールナー":  "Braixen",
	"マフォクシー": "Delphox",
	"ケロマツ":   "Froakie",
	"ゲコガシラ":  "Frogadier",
	"ゲッコウガ":  "Greninja",
	"ホルビー":   "Bunnelby",
	"ホルード":   "Diggersby",
	"ヤヤコマ":   "Fletchling",
	"ヒノヤコマ":  "Fletchinder",
	"ファイアロー": "Talonflame",
	"コフキムシ":  "Scatterbug",
	"コフーライ":  "Spewpa",
	"ビビヨン":   "Vivillon",
	"シシコ":    "Litleo",
	"カエンジシ":  "Pyroar",
	"フラベベ":   "Flabébé",
	"フラエッテ":  "Floette",
	"フラージェス": "Florges",
	"メェークル":  "Skiddo",
	"ゴーゴート":  "Gogoat",
	"ヤンチャム":  "Pancham",
	"ゴロンダ":   "Pangoro",
	"トリミアン":  "Furfrou",
	"ニャスパー":  "Espurr",
	"ニャオニクス": "Meowstic",
	"ヒトツキ":   "Honedge",
	"ニダンギル":  "Doublade",
	"ギルガルド":  "Aegislash",
	"シュシュプ":  "Spritzee",
	"フレフワン":  "Aromatisse",
	"ペロッパフ":  "Swirlix",
	"ペロリーム":  "Slurpuff",
	"マーイーカ":  "Inkay",
	"カラマネロ":  "Malamar",
	"カメテテ":   "Binacle",
	"ガメノデス":  "Barbaracle",
	"クズモー":   "Skrelp",
	"ドラミドロ":  "Dragalge",
	"ウデッポウ":  "Clauncher",
	"ブロスター":  "Clawitzer",
	"エリキテル":  "Helioptile",
	"エレザード":  "Heliolisk",
	"チゴラス":   "Tyrunt",
	"ガチゴラス":  "Tyrantrum",
	"アマルス":   "Amaura",
	"アマルルガ":  "Aurorus",
	"ニンフィア":  "Sylveon",
	"ルチャブル":  "Hawlucha",
	"デデンネ":   "Dedenne",
	"メレシー":   "Carbink",
	"ヌメラ":    "Goomy",
	"ヌメイル":   "Sliggoo",
	"ヌメルゴン":  "Goodra",
	"クレッフィ":  "Klefki",
	"ボクレー":   "Phantump",
	"オーロット":  "Trevenant",
	"バケッチャ":  "Pumpkaboo",
	"パンプジン":  "Gourgeist",
	"カチコール":  "Bergmite",
	"クレベース":  "Avalugg",
	"オンバット":  "Noibat",
	"オンバーン":  "Noivern",
	"ゼルネアス":  "Xerneas",
	"イベルタル":  "Yveltal",
	"ジガルデ":   "Zygarde",
	"ディアンシー": "Diancie",
	"フーパ":    "Hoopa",
	"ボルケニオン": "Volcanion",

	// Gen 7 Pokemon (722-809)
	"モクロー":   "Rowlet",
	"フクスロー":  "Dartrix",
	"ジュナイパー": "Decidueye",
	"ニャビー":   "Litten",
	"ニャヒート":  "Torracat",
	"ガオガエン":  "Incineroar",
	"アシマリ":   "Popplio",
	"オシャマリ":  "Brionne",
	"アシレーヌ":  "Primarina",
	"ツツケラ":   "Pikipek",
	"ケララッパ":  "Trumbeak",
	"ドデカバシ":  "Toucannon",
	"ヤングース":  "Yungoos",
	"デカグース":  "Gumshoos",
	"アゴジムシ":  "Grubbin",
	"デンヂムシ":  "Charjabug",
	"クワガノン":  "Vikavolt",
	"マケンカニ":  "Crabrawler",
	"ケケンカニ":  "Crabominable",
	"オドリドリ":  "Oricorio",
	"アブリー":   "Cutiefly",
	"アブリボン":  "Ribombee",
	"イワンコ":   "Rockruff",
	"ルガルガン":  "Lycanroc",
	"ヨワシ":    "Wishiwashi",
	"ヒドイデ":   "Mareanie",
	"ドヒドイデ":  "Toxapex",
	"ドロバンコ":  "Mudbray",
	"バンバドロ":  "Mudsdale",
	"シズクモ":   "Dewpider",
	"オニシズクモ": "Araquanid",
	"カリキリ":   "Fomantis",
	"ラランテス":  "Lurantis",
	"ネマシュ":   "Morelull",
	"マシェード":  "Shiinotic",
	"ヤトウモリ":  "Salandit",
	"エンニュート": "Salazzle",
	"ヌイコグマ":  "Stufful",
	"キテルグマ":  "Bewear",
	"アマカジ":   "Bounsweet",
	"アママイコ":  "Steenee",
	"アマージョ":  "Tsareena",
	"キュワワー":  "Comfey",
	"ヤレユータン": "Oranguru",
	"ナゲツケサル": "Passimian",
	"コソクムシ":  "Wimpod",
	"グソクムシャ": "Golisopod",
	"スナバァ":   "Sandygast",
	"シロデスナ":  "Palossand",
	"ナマコブシ":  "Pyukumuku",
	"タイプ：ヌル": "Type: Null",
	"シルヴァディ": "Silvally",
	"メテノ":    "Minior",
	"ネッコアラ":  "Komala",
	"バクガメス":  "Turtonator",
	"トゲデマル":  "Togedemaru",
	"ミミッキュ":  "Mimikyu",
	"ハギギシリ":  "Bruxish",
	"ジジーロン":  "Drampa",
	"ダダリン":   "Dhelmise",
	"ジャラコ":   "Jangmo-o",
	"ジャランゴ":  "Hakamo-o",
	"ジャラランガ": "Kommo-o",
	"カプ・コケコ": "Tapu Koko",
	"カプ・テテフ": "Tapu Lele",
	"カプ・ブルル": "Tapu Bulu",
	"カプ・レヒレ": "Tapu Fini",
	"コスモッグ":  "Cosmog",
	"コスモウム":  "Cosmoem",
	"ソルガレオ":  "Solgaleo",
	"ルナアーラ":  "Lunala",
	"ウツロイド":  "Nihilego",
	"マッシブーン": "Buzzwole",
	"フェローチェ": "Pheromosa",
	"デンジュモク": "Xurkitree",
	"テッカグヤ":  "Celesteela",
	"カミツルギ":  "Kartana",
	"アクジキング": "Guzzlord",
	"ネクロズマ":  "Necrozma",
	"マギアナ":   "Magearna",
	"マーシャドー": "Marshadow",
	"ベベノム":   "Poipole",
	"アーゴヨン":  "Naganadel",
	"ツンデツンデ": "Stakataka",
	"ズガドーン":  "Blacephalon",
	"ゼラオラ":   "Zeraora",
	"メルタン":   "Meltan",
	"メルメタル":  "Melmetal",

	// Gen 8 Pokemon (810-905)
	"サルノリ":   "Grookey",
	"バチンキー":  "Thwackey",
	"ゴリランダー": "Rillaboom",
	"ヒバニー":   "Scorbunny",
	"ラビフット":  "Raboot",
	"エースバーン": "Cinderace",
	"メッソン":   "Sobble",
	"ジメレオン":  "Drizzile",
	"インテレオン": "Inteleon",
	"ホシガリス":  "Skwovet",
	"ヨクバリス":  "Greedent",
	"ココガラ":   "Rookidee",
	"アオガラス":  "Corvisquire",
	"アーマーガア": "Corviknight",
	"サッチムシ":  "Blipbug",
	"レドームシ":  "Dottler",
	"イオルブ":   "Orbeetle",
	"クスネ":    "Nickit",
	"フォクスライ": "Thievul",
	"ヒメンカ":   "Gossifleur",
	"ワタシラガ":  "Eldegoss",
	"ウールー":   "Wooloo",
	"バイウールー": "Dubwool",
	"カムカメ":   "Chewtle",
	"カジリガメ":  "Drednaw",
	"ワンパチ":   "Yamper",
	"パルスワン":  "Boltund",
	"タンドン":   "Rolycoly",
	"トロッゴン":  "Carkol",
	"セキタンザン": "Coalossal",
	"カジッチュ":  "Applin",
	"アップリュー": "Flapple",
	"タルップル":  "Appletun",
	"スナヘビ":   "Silicobra",
	"サダイジャ":  "Sandaconda",
	"ウッウ":    "Cramorant",
	"サシカマス":  "Arrokuda",
	"カマスジョー": "Barraskewda",
	"エレズン":   "Toxel",
	"ストリンダー": "Toxtricity",
	"ヤクデ":    "Sizzlipede",
	"マルヤクデ":  "Centiskorch",
	"タタッコ":   "Clobbopus",
	"オトスパス":  "Grapploct",
	"ヤバチャ":   "Sinistea",
	"ポットデス":  "Polteageist",
	"ミブリム":   "Hatenna",
	"テブリム":   "Hattrem",
	"ブリムオン":  "Hatterene",
	"ベロバー":   "Impidimp",
	"ギモー":    "Morgrem",
	"オーロンゲ":  "Grimmsnarl",
	"タチフサグマ": "Obstagoon",
	"ニャイキング": "Perrserker",
	"サニゴーン":  "Cursola",
	"ネギガナイト": "Sirfetch'd",
	"バリコオル":  "Mr. Rime",
	"デスバーン":  "Runerigus",
	"マホミル":   "Milcery",
	"マホイップ":  "Alcremie",
	"タイレーツ":  "Falinks",
	"バチンウニ":  "Pincurchin",
	"ユキハミ":   "Snom",
	"モスノウ":   "Frosmoth",
	"イシヘンジン": "Stonjourner",
	"コオリッポ":  "Eiscue",
	"イエッサン":  "Indeedee",
	"モルペコ":   "Morpeko",
	"ゾウドウ":   "Cufant",
	"ダイオウドウ": "Copperajah",
	"パッチラゴン": "Dracozolt",
	"パッチルドン": "Arctozolt",
	"ウオノラゴン": "Dracovish",
	"ウオチルドン": "Arctovish",
	"ジュラルドン": "Duraludon",
	"ドラメシヤ":  "Dreepy",
	"ドロンチ":   "Drakloak",
	"ドラパルト":  "Dragapult",
	"ザシアン":   "Zacian",
	"ザマゼンタ":  "Zamazenta",
	"ムゲンダイナ": "Eternatus",
	"ダクマ":    "Kubfu",
	"ウーラオス":  "Urshifu",
	"ザルード":   "Zarude",
	"レジエレキ":  "Regieleki",
	"レジドラゴ":  "Regidrago",
	"ブリザポス":  "Glastrier",
	"レイスポス":  "Spectrier",
	"バドレックス": "Calyrex",
	"アヤシシ":   "Wyrdeer",
	"バサギリ":   "Kleavor",
	"ガチグマ":   "Ursaluna",
	"イダイトウ":  "Basculegion",
	"オオニューラ": "Sneasler",
	"ハリーマン":  "Overqwil",
	"ラブトロス":  "Enamorus",

	// Gen 9 Pokemon (906-1025)
	"ニャオハ":   "Sprigatito",
	"ニャローテ":  "Floragato",
	"マスカーニャ": "Meowscarada",
	"ホゲータ":   "Fuecoco",
	"アチゲータ":  "Crocalor",
	"ラウドボーン": "Skeledirge",
	"クワッス":   "Quaxly",
	"ウェルカモ":  "Quaxwell",
	"ウェーニバル": "Quaquaval",
	"グルトン":   "Lechonk",
	"パフュートン": "Oinkologne",
	"タマンチュラ": "Tarountula",
	"ワナイダー":  "Spidops",
	"マメバッタ":  "Nymble",
	"エクスレッグ": "Lokix",
	"パモ":     "Pawmi",
	"パモット":   "Pawmo",
	"パーモット":  "Pawmot",
	"ワッカネズミ": "Tandemaus",
	"イッカネズミ": "Maushold",
	"パピモッチ":  "Fidough",
	"バウッツェル": "Dachsbun",
	"ミニーブ":   "Smoliv",
	"オリーニョ":  "Dolliv",
	"オリーヴァ":  "Arboliva",
	"イキリンコ":  "Squawkabilly",
	"コジオ":    "Nacli",
	"ジオヅム":   "Naclstack",
	"キョジオーン": "Garganacl",
	"カルボウ":   "Charcadet",
	"グレンアルマ": "Armarouge",
	"ソウブレイズ": "Ceruledge",
	"ズピカ":    "Tadbulb",
	"ハラバリー":  "Bellibolt",
	"カイデン":   "Wattrel",
	"タイカイデン": "Kilowattrel",
	"オラチフ":   "Maschiff",
	"マフィティフ": "Mabosstiff",
	"シルシュルー": "Shroodle",
	"タギングル":  "Grafaiai",
	"アノクサ":   "Bramblin",
	"アノホラグサ": "Brambleghast",
	"ノノクラゲ":  "Toedscool",
	"リククラゲ":  "Toedscruel",
	"ガケガニ":   "Klawf",
	"カプサイジ":  "Capsakid",
	"スコヴィラン": "Scovillain",
	"シガロコ":   "Rellor",
	"ベラカス":   "Rabsca",
	"ヒラヒナ":   "Flittle",
	"クエスパトラ": "Espathra",
	"カヌチャン":  "Tinkatink",
	"ナカヌチャン": "Tinkatuff",
	"デカヌチャン": "Tinkaton",
	"ウミディグダ": "Wiglett",
	"ウミトリオ":  "Wugtrio",
	"オトシドリ":  "Bombirdier",
	"ナミイルカ":  "Finizen",
	"イルカマン":  "Palafin",
	"ブロロン":   "Varoom",
	"ブロロローム": "Revavroom",
	"モトトカゲ":  "Cyclizar",
	"ミミズズ":   "Orthworm",
	"キラーメ":   "Glimmet",
	"キラフロル":  "Glimmora",
	"ボチ":     "Greavard",
	"ハカドッグ":  "Houndstone",
	"カラミンゴ":  "Flamigo",
	"アルクジラ":  "Cetoddle",
	"ハルクジラ":  "Cetitan",
	"ミガルーサ":  "Veluza",
	"ヘイラッシャ": "Dondozo",
	"シャリタツ":  "Tatsugiri",
	"コノヨザル":  "Annihilape",
	"ドオー":    "Clodsire",
	"リキキリン":  "Farigiraf",
	"ノココッチ":  "Dudunsparce",
	"ドドゲザン":  "Kingambit",
	"イダイナキバ": "Great Tusk",
	"サケブシッポ": "Scream Tail",
	"アラブルタケ": "Brute Bonnet",
	"ハバタクカミ": "Flutter Mane",
	"チヲハウハネ": "Slither Wing",
	"スナノケガワ": "Sandy Shocks",
	"テツノワダチ": "Iron Treads",
	"テツノツツミ": "Iron Bundle",
	"テツノカイナ": "Iron Hands",
	"テツノコウベ": "Iron Jugulis",
	"テツノドクガ": "Iron Moth",
	"テツノイバラ": "Iron Thorns",
	"セビエ":    "Frigibax",
	"セゴール":   "Arctibax",
	"セグレイブ":  "Baxcalibur",
	"コレクレー":  "Gimmighoul",
	"サーフゴー":  "Gholdengo",
	"チオンジェン": "Wo-Chien",
	"パオジアン":  "Chien-Pao",
	"ディンルー":  "Ting-Lu",
	"イーユイ":   "Chi-Yu",
	"トドロクツキ": "Roaring Moon",
	"テツノブジン": "Iron Valiant",
	"コライドン":  "Koraidon",
	"ミライドン":  "Miraidon",
	"ウネルミナモ": "Walking Wake",
	"テツノイサハ": "Iron Leaves",
	"カミッチュ":  "Dipplin",
	"チャデス":   "Poltchageist",
	"ヤバソチャ":  "Sinistcha",
	"イイネイヌ":  "Okidogi",
	"マシマシラ":  "Munkidori",
	"キチキギス":  "Fezandipiti",
	"オーガポン":  "Ogerpon",
	"ブリジュラス": "Archaludon",
	"カミツオロチ": "Hydrapple",
	"ウガツホムラ": "Gouging Fire",
	"タケルライコ": "Raging Bolt",
	"テツノイワオ": "Iron Boulder",
	"テツノカシラ": "Iron Crown",
	"テラパゴス":  "Terapagos",
	"モモワロウ":  "Pecharunt",

	// Regional Form Pokemon
	// =====================

	// Alolan Forms (Sun & Moon, 2016)
	"アローラライチュウ": "Alolan Raichu",
	"アローラロコン":   "Alolan Vulpix",
	"アローラキュウコン": "Alolan Ninetales",
	"アローラサンド":   "Alolan Sandshrew",
	"アローラサンドパン": "Alolan Sandslash",
	"アローラディグダ":  "Alolan Diglett",
	"アローラダグトリオ": "Alolan Dugtrio",
	"アローラニャース":  "Alolan Meowth",
	"アローラペルシアン": "Alolan Persian",
	"アローライシツブテ": "Alolan Geodude",
	"アローラゴローン":  "Alolan Graveler",
	"アローラゴローニャ": "Alolan Golem",
	"アローラベトベター": "Alolan Grimer",
	"アローラベトベトン": "Alolan Muk",
	"アローラナッシー":  "Alolan Exeggutor",
	"アローラガラガラ":  "Alolan Marowak",
	"アローラコラッタ":  "Alolan Rattata",
	"アローララッタ":   "Alolan Raticate",

	// Galarian Forms (Sword & Shield, 2019)
	"ガラルポニータ":  "Galarian Ponyta",
	"ガラルギャロップ": "Galarian Rapidash",
	"ガラルカモネギ":  "Galarian Farfetch'd",
	"ガラルヤドン":   "Galarian Slowpoke",
	"ガラルヤドラン":  "Galarian Slowbro",
	"ガラルヤドキング": "Galarian Slowking",
	"ガラルマタドガス": "Galarian Weezing",
	"ガラルサニーゴ":  "Galarian Corsola",
	"ガラルジグザグマ": "Galarian Zigzagoon",
	"ガラルマッスグマ": "Galarian Linoone",
	"ガラルダルマッカ": "Galarian Darumaka",
	"ガラルヒヒダルマ": "Galarian Darmanitan",
	"ガラルデスマス":  "Galarian Yamask",
	"ガラルマッギョ":  "Galarian Stunfisk",
	"ガラルバリヤード": "Galarian Mr. Mime",
	"ガラルニャース":  "Galarian Meowth",
	"ガラルサンダー":  "Galarian Zapdos",
	"ガラルファイヤー": "Galarian Moltres",
	"ガラルフリーザー": "Galarian Articuno",

	// Hisuian Forms (Legends: Arceus, 2022)
	"ヒスイガーディ":   "Hisuian Growlithe",
	"ヒスイウインディ":  "Hisuian Arcanine",
	"ヒスイビリリダマ":  "Hisuian Voltorb",
	"ヒスイマルマイン":  "Hisuian Electrode",
	"ヒスイバクフーン":  "Hisuian Typhlosion",
	"ヒスイダイケンキ":  "Hisuian Samurott",
	"ヒスイジュナイパー": "Hisuian Decidueye",
	"ヒスイゾロア":    "Hisuian Zorua",
	"ヒスイゾロアーク":  "Hisuian Zoroark",
	"ヒスイハリーセン":  "Hisuian Qwilfish",
	"ヒスイニューラ":   "Hisuian Sneasel",
	"ヒスイドレディア":  "Hisuian Lilligant",
	"ヒスイウォーグル":  "Hisuian Braviary",
	"ヒスイヌメイル":   "Hisuian Sliggoo",
	"ヒスイヌメルゴン":  "Hisuian Goodra",
	"ヒスイクレベース":  "Hisuian Avalugg",

	// Paldean Forms (Scarlet & Violet, 2022)
	"パルデアウパー":   "Paldean Wooper",
	"パルデアケンタロス": "Paldean Tauros",

	// Pokemon Trainer Cards by Era (earliest first)
	// ===========================================

	// Base Set / Jungle / Fossil / Base Set 2 Era (1996-1999)
	"オーキドはかせ":    "Professor Oak",
	"マサキ":        "Bill",
	"ポケモンいれかえ":   "Switch",
	"モンスターボール":   "Poké Ball",
	"プラスパワー":     "PlusPower",
	"ディフェンダー":    "Defender",
	"エネルギーリムーブ":  "Energy Removal",
	"突風":         "Gust of Wind",
	"パソコン通信":     "Computer Search",
	"アイテムファインダー": "Item Finder",
	"ポケモン回収":     "Scoop Up",
	"エネルギー回収":    "Energy Retrieval",
	"きずぐすり":      "Potion",
	"いいきずぐすり":    "Super Potion",
	"げんきのかけら":    "Revive",
	"ポケモンセンター":   "Pokémon Center",
	"ポケモン図鑑":     "Pokédex",
	"ポケモン通信":     "Pokémon Trader",
	"ギャンブラー":     "Gambler",
	"なにかの化石":     "Mysterious Fossil",
	"ポケモンブリーダー":  "Pokémon Breeder",
	"育て屋さん":      "Pokémon Breeder",
	"リサイクル":      "Recycle",
	"夜の廃品回収":     "Nightly Garbage Run",

	// Gym Heroes / Gym Challenge Era (1998-2000)
	// Gym Leader Name Prefixes (for possessive forms like "Misty's")
	"カスミの": "Misty's",
	"タケシの": "Brock's",
	"マチスの": "Lt. Surge's",
	"エリカの": "Erika's",
	"ナツメの": "Sabrina's",
	"キョウの": "Koga's",
	"カツラの": "Blaine's",
	"サカキの": "Giovanni's",
	// Gym Leader Trainer Cards
	"カスミのいかり":      "Misty's Wrath",
	"カスミのねがい":      "Misty's Wish",
	"カスミのおねがい":     "Misty's Request",
	"タケシのきあい":      "Brock's Grit",
	"マチスのひみつメカ":    "Lt. Surge's Secret Plan",
	"マチスの交渉":       "Lt. Surge's Treaty",
	"エリカのやさしさ":     "Erika's Kindness",
	"ナツメのまなざし":     "Sabrina's Gaze",
	"ナツメのサイキック":    "Sabrina's Psychic Control",
	"キョウのワナ":       "Koga's Ninja Trick",
	"カツラのクイズ":      "Blaine's Quiz",
	"カツラのさいごのきりふだ": "Blaine's Last Resort",
	"サカキのけいかく":     "Giovanni's Scheme",
	"サカキのたくらみ":     "Giovanni's Scheme",
	// Gym Stadiums
	"ニビシティジム":   "Pewter City Gym",
	"ハナダシティジム":  "Cerulean City Gym",
	"クチバシティジム":  "Vermilion City Gym",
	"タマムシシティジム": "Celadon City Gym",
	"ヤマブキシティジム": "Saffron City Gym",
	"セキチクシティジム": "Fuchsia City Gym",
	"グレンタウンジム":  "Cinnabar Island Gym",
	"トキワシティジム":  "Viridian City Gym",
	// Gym Leader Pokemon (common ones)
	"カスミのスターミー": "Misty's Starmie",
	"カスミのコダック":  "Misty's Psyduck",
	"カスミのギャラドス": "Misty's Gyarados",
	"タケシのイワーク":  "Brock's Onix",
	"タケシのイシツブテ": "Brock's Geodude",
	"エリカのモンジャラ": "Erika's Tangela",
	"エリカのラフレシア": "Erika's Vileplume",
	"マチスのピカチュウ": "Lt. Surge's Pikachu",
	"マチスのライチュウ": "Lt. Surge's Raichu",
	"マチスのエレブー":  "Lt. Surge's Electabuzz",
	"ナツメのフーディン": "Sabrina's Alakazam",
	"キョウのベトベトン": "Koga's Muk",
	"キョウのマタドガス": "Koga's Weezing",
	"カツラのウインディ": "Blaine's Arcanine",
	"カツラのファイヤー": "Blaine's Moltres",
	"カツラのリザードン": "Blaine's Charizard",
	"カツラのリザード":  "Blaine's Charmeleon",
	"カツラのヒトカゲ":  "Blaine's Charmander",
	"サカキのニドキング": "Giovanni's Nidoking",
	"サカキのペルシアン": "Giovanni's Persian",
	"サカキのミュウツー": "Giovanni's Mewtwo",
	// Rocket Cards
	"ロケット団のおねーさん": "Rocket's Sneak Attack",
	"ロケット団のワナ":    "Rocket's Trap",
	"ロケット団参上!":    "Here Comes Team Rocket!",

	// Neo Era (2000-2002)
	"ウツギはかせ":       "Professor Elm",
	"エネルギーサーキュレート": "Energy Flow",
	"すごいつりざお":      "Super Rod",
	"いのちのしずく":      "Focus Band",
	"時のとう":         "Sprout Tower",
	"やみのせきひん":      "Dark Energy",

	// E-Card Era (2001-2003)
	"タウンボランティア":     "Town Volunteers",
	"オーキドはかせのけんきゅう": "Professor Oak's Research",
	"コピーキャット":       "Copycat",

	// EX Era (2003-2007)
	"テレビレポーター":     "TV Reporter",
	"スティーブンのアドバイス": "Steven's Advice",
	"ふしぎなアメ":       "Rare Candy",
	"ふしぎなあめ":       "Rare Candy",

	// Diamond & Pearl Era (2007-2011)
	"シロナ":       "Cynthia",
	"アカギ":       "Cyrus",
	"ポケモンコレクター": "Pokémon Collector",
	"やまおとこ":     "Hiker",
	"クイックボール":   "Quick Ball",
	"ハイパーボール":   "Ultra Ball",

	// Black & White Era (2011-2013)
	"N":          "N",
	"アララギはかせ":    "Professor Juniper",
	"アイリス":       "Iris",
	"デント":        "Cilan",
	"ベル":         "Bianca",
	"チェレン":       "Cheren",
	"フウロ":        "Skyla",
	"アクロマ":       "Colress",
	"プラズマ団のしたっぱ": "Team Plasma Grunt",
	"カトレア":       "Caitlin",
	"ランダムレシーバー":  "Random Receiver",
	"ポケモンキャッチャー": "Pokémon Catcher",
	"ダークパッチ":     "Dark Patch",
	"レベルボール":     "Level Ball",
	"ヘビーボール":     "Heavy Ball",

	// XY Era (2013-2016)
	"プラターヌはかせ":  "Professor Sycamore",
	"セレナ":       "Serena",
	"カルネ":       "Diantha",
	"コルニ":       "Korrina",
	"フラダリ":      "Lysandre",
	"ティエルノ":     "Tierno",
	"トロバ":       "Trevor",
	"バトルサーチャー":  "VS Seeker",
	"トレーナーズメール": "Trainers' Mail",
	"ちからのハチマキ":  "Muscle Band",
	"こだわりハチマキ":  "Choice Band",
	"かるいし":      "Float Stone",

	// Sun & Moon Era (2016-2019)
	"リーリエ":       "Lillie",
	"ハウ":         "Hau",
	"グラジオ":       "Gladion",
	"ルザミーネ":      "Lusamine",
	"グズマ":        "Guzma",
	"アセロラ":       "Acerola",
	"マーマネ":       "Sophocles",
	"マオ":         "Mallow",
	"スイレン":       "Lana",
	"カキ":         "Kiawe",
	"ククイはかせ":     "Professor Kukui",
	"エリカのおもてなし":  "Erika's Hospitality",
	"ポケギア3.0":    "Pokégear 3.0",
	"カスタムキャッチャー": "Custom Catcher",
	"エレキパワー":     "Electropower",
	"ネストボール":     "Nest Ball",
	"あなぬけのヒモ":    "Escape Rope",
	"こだわりベルト":    "Choice Belt",
	"ともだちてちょう":   "Pal Pad",
	"シロナ&カトレア":   "Cynthia & Caitlin",
	"レッド&グリーン":   "Red & Blue",

	// Sword & Shield Era (2019-2023)
	"マリィ":       "Marnie",
	"ホップ":       "Hop",
	"ダンデ":       "Leon",
	"ソニア":       "Sonia",
	"ビート":       "Bede",
	"ローズ":       "Rose",
	"ネズ":        "Piers",
	"ルリナ":       "Nessa",
	"サイトウ":      "Bea",
	"オニオン":      "Allister",
	"メロン":       "Melony",
	"マクワ":       "Gordie",
	"ポプラ":       "Opal",
	"キバナ":       "Raihan",
	"クララ":       "Klara",
	"セイボリー":     "Avery",
	"ピオニー":      "Peony",
	"ボールガイ":     "Ball Guy",
	"博士の研究":     "Professor's Research",
	"ボスの指令":     "Boss's Orders",
	"マリィのプライド":  "Marnie's Pride",
	"しんかのおこう":   "Evolution Incense",
	"ふうせん":      "Air Balloon",
	"おおきなおまもり":  "Big Charm",
	"ツールスクラッパー": "Tool Scrapper",
	"頂への雪道":     "Path to the Peak",
	"崩れたスタジアム":  "Collapsed Stadium",
	"シンオウ神殿":    "Temple of Sinnoh",
	"トレーニングコート": "Training Court",
	"ジムトレーナー":   "Gym Trainer",
	"冒険家の発見":    "Adventurer's Discovery",
	"かがやくポケモン":  "Radiant Pokémon",
	"ツツジ":       "Roxanne",
	"カイ":        "Irida",
	"セキ":        "Adaman",
	"ヒナツ":       "Grant",
	"キョウ":       "Janine",
	"キャンプセット":   "Camping Gear",
	"げんきのかたまり":  "Max Revive",
	"すごいきずぐすり":  "Hyper Potion",
	"まんたんのくすり":  "Max Potion",

	// Scarlet & Violet Era (2023-present)
	"ナンジャモ":       "Iono",
	"ネモ":          "Nemona",
	"ペパー":         "Arven",
	"ボタン":         "Penny",
	"クラベル":        "Clavell",
	"ジニア":         "Jacq",
	"オモダカ":        "Geeta",
	"カエデ":         "Katy",
	"コルサ":         "Brassius",
	"ハイダイ":        "Kofu",
	"アオキ":         "Larry",
	"リップ":         "Rika",
	"チリ":          "Rika",
	"グルーシャ":       "Grusha",
	"ポピー":         "Poppy",
	"ハッサク":        "Hassel",
	"オーリム":        "Professor Sada",
	"フトゥー":        "Professor Turo",
	"バトルVIPパス":    "Battle VIP Pass",
	"なかよしポフィン":    "Buddy-Buddy Poffin",
	"大地の器":        "Earthen Vessel",
	"夜のタンカ":       "Night Stretcher",
	"カウンターキャッチャー": "Counter Catcher",
	"プライムキャッチャー":  "Prime Catcher",
	"ポケモンリーグ本部":   "Pokémon League Headquarters",
	"ボウルタウン":      "Artazon",
	"テーブルシティ":     "Mesagoza",
	"ロストシティ":      "Lost City",
	"ロストスイーパー":    "Lost Vacuum",
	"ミモザ":         "Miriam",
	"ジャッジマン":      "Judge",
	"ナタネの活気":      "Gardenia's Vigor",
	"おはやし笛":       "Flute",
	"テクニカルマシン":    "Technical Machine",
	"エヴォリューション":   "Evolution",
	"ワザマシン":       "TM",
	"リバーサルエネルギー":  "Reversal Energy",
	"ジェットエネルギー":   "Jet Energy",
	"ギフトエネルギー":    "Gift Energy",
	"セラピーエネルギー":   "Therapeutic Energy",
	"ルミナスエネルギー":   "Luminous Energy",

	// Anime Characters (for trainer cards featuring them)
	"サトシ":   "Ash",
	"ロケット団": "Team Rocket",
	"ムサシ":   "Jessie",
	"コジロウ":  "James",

	// Energy Cards
	"基本草エネルギー":     "Grass Energy",
	"基本炎エネルギー":     "Fire Energy",
	"基本水エネルギー":     "Water Energy",
	"基本雷エネルギー":     "Lightning Energy",
	"基本超エネルギー":     "Psychic Energy",
	"基本闘エネルギー":     "Fighting Energy",
	"基本悪エネルギー":     "Darkness Energy",
	"基本鋼エネルギー":     "Metal Energy",
	"基本フェアリーエネルギー": "Fairy Energy",
	"無色エネルギー":      "Colorless Energy",
	"ダブル無色エネルギー":   "Double Colorless Energy",
}

// TranslateJapaneseName attempts to translate a Japanese card name to English.
// Returns the English name and true if found, or empty string and false if not.
func TranslateJapaneseName(japaneseName string) (string, bool) {
	// Try exact match first
	if englishName, ok := JapaneseToEnglishNames[japaneseName]; ok {
		return englishName, true
	}

	// Try with common suffixes removed (V, VMAX, ex, GX, etc.)
	// Only match if the input actually ends with the suffix (case-insensitive check)
	suffixes := []string{"V", "VMAX", "VSTAR", "ex", "EX", "GX", "δ", "★"}
	for _, suffix := range suffixes {
		if len(japaneseName) > len(suffix) {
			// Check if the input actually ends with this suffix (case-insensitive)
			inputEnd := japaneseName[len(japaneseName)-len(suffix):]
			if !strings.EqualFold(inputEnd, suffix) {
				continue
			}
			baseName := japaneseName[:len(japaneseName)-len(suffix)]
			if englishName, ok := JapaneseToEnglishNames[baseName]; ok {
				return englishName + " " + suffix, true
			}
		}
	}

	// Apply OCR corrections and try again
	corrected := applyJapaneseOCRCorrections(japaneseName)
	if corrected != japaneseName {
		if englishName, ok := JapaneseToEnglishNames[corrected]; ok {
			return englishName, true
		}
	}

	// Special handling for Nidoran - OCR often corrupts the gender symbol
	// ニドラン followed by any character (or nothing) should match
	if strings.HasPrefix(japaneseName, "ニドラン") {
		// Check what follows ニドラン
		suffix := strings.TrimPrefix(japaneseName, "ニドラン")
		// Map common OCR corruptions of gender symbols
		switch suffix {
		case "♂", "d", "♪", "』", "」", ")", "J", "]":
			return "Nidoran ♂", true
		case "♀", "e", "Q", "『", "「", "(", "[":
			return "Nidoran ♀", true
		case "": // No gender - default to male (more common)
			return "Nidoran ♂", true
		}
	}

	return "", false
}

// applyJapaneseOCRCorrections fixes common OCR misreads in Japanese text
func applyJapaneseOCRCorrections(text string) string {
	// First normalize dashes/hyphens to katakana long vowel mark (ー)
	// OCR often misreads ー as various dash characters
	dashVariants := []string{
		"-", // Hyphen-minus U+002D
		"–", // En dash U+2013
		"—", // Em dash U+2014
		"－", // Fullwidth hyphen-minus U+FF0D
		"一", // CJK unified ideograph "one" (sometimes OCR mistake)
	}
	result := text
	for _, dash := range dashVariants {
		result = strings.ReplaceAll(result, dash, "ー")
	}

	// Common OCR substitutions for Japanese hiragana/katakana
	corrections := map[string]string{
		// Hiragana corrections
		"すこい": "すごい", // ko -> go (e.g., すごいつりざお = Super Rod)
		"こつ":  "ごつ",  // ko -> go
		"つこ":  "つご",  // ko -> go
		// Common misreads
		"りさお": "りざお", // sa -> za
		"つりさ": "つりざ", // sa -> za
	}

	for wrong, correct := range corrections {
		result = strings.ReplaceAll(result, wrong, correct)
	}
	return result
}
